services:
  - type: web
    name: prompthub-backend
    env: docker
    # Docker 설정
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    # 포트 설정
    port: 8000
    # 헬스체크 설정
    healthCheckPath: /api/core/health/
    # 환경변수 설정
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "prompthub-backend.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-frontend-domain.com"
    # 자동 배포 설정
    autoDeploy: true
    # 빌드 필터 (backend 폴더 변경시만 재배포)
    buildFilter:
      paths:
        - backend/**

# PostgreSQL 데이터베이스
databases:
  - name: prompthub-db
    databaseName: prompthub
    user: prompthub_user
    region: oregon

# Docker 배포 장점:
# 1. 일관된 환경: 로컬과 동일한 환경에서 실행
# 2. 의존성 격리: 모든 의존성이 컨테이너에 포함됨
# 3. 빠른 배포: 이미지 캐싱으로 재배포 속도 향상
# 4. 헬스체크: 자동 상태 모니터링
# 5. 확장성: 쉬운 수평 확장 지원
