services:
  - type: web
    name: prompthub-backend
    env: python
    # backend 폴더가 Django 프로젝트 루트
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
    # render가 자동으로 제공하는 PostgreSQL 데이터베이스 연결
    # 환경변수 DATABASE_URL이 자동으로 설정됨

  # PostgreSQL 데이터베이스 (선택사항 - render에서 자동 생성 가능)
databases:
  - name: prompthub-db
    databaseName: prompthub
    user: prompthub_user

# 환경변수 설정 가이드:
# render 대시보드에서 다음 환경변수들을 설정하세요:
# - SECRET_KEY: Django 시크릿 키 (자동 생성 권장)
# - DJANGO_ALLOWED_HOSTS: 여러분의 render 도메인 (예: yourapp.onrender.com)
# - CORS_ALLOWED_ORIGINS: 프론트엔드 도메인 (있을 경우)
# - CSRF_TRUSTED_ORIGINS: 프론트엔드 도메인 (있을 경우)
