import { PostDetail } from '@/types/datatype_sample'

export const samplePostDetails: PostDetail[] = [
  {
    id: 1,
    title: '데이터 분석 리뷰',
    author: 'Admin',
    authorInitial: 'A',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-15T10:30:00Z',
    views: 1500,
    satisfaction: 4.5,
    likes: 25,
    isLiked: true,
    bookmarks: 10,
    isBookmarked: false,
    platform: 'OpenAI',
    model: 'o3',
    model_etc: '',
    category: '데이터/분석',
    category_etc: '',
    tags: ['데이터 분석', 'AI'],
    prompt:
      '지난 분기 판매 데이터를 분석하여 가장 성과가 좋은 제품 카테고리를 식별하고, 그 성공 요인에 대한 통찰을 제공해 주세요.',
    aiResponse:
      '지난 분기 판매 데이터를 분석한 결과, 전자제품과 가전제품이 가장 높은 성과를 보였습니다. 전자제품은 새로운 스마트폰 모델 출시와 공격적인 마케팅 캠페인으로 인해 15% 매출 증가를 기록했습니다. 가전제품은 계절적 수요로 인해 10% 성장했습니다.',
    additionalOpinion:
      '명확하고 간결한 분석을 제공하여 주요 트렌드와 요인을 강조했습니다. 통찰이 실행 가능하여 다음 마케팅 전략에 도움이 되었습니다.',
    isAuthor: true,
  },
  {
    id: 2,
    title: '창의적 스토리텔링',
    author: 'StoryCrafter',
    authorInitial: 'S',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-01T14:20:00Z',
    views: 3200,
    satisfaction: 3.5,
    likes: 50,
    isLiked: false,
    bookmarks: 20,
    isBookmarked: true,
    platform: 'Anthropic',
    model: '기타',
    model_etc: 'Claude 4 Custom',
    category: '창작/글쓰기',
    category_etc: '',
    tags: ['스토리텔링', '창의성'],
    prompt:
      '젊은 마법사가 자신의 능력을 제어하는 법을 배우는 판타지 세계를 배경으로 한 단편 소설을 작성해 주세요. 갈등과 해결을 포함해 주세요.',
    aiResponse:
      '엘도리아라는 신비로운 땅에서, 12살의 아리아는 자신의 마법 능력을 발견했습니다. 능력을 제어하지 못해 실수로 용을 소환하여 마을을 위협하게 됩니다. 멘토 엘드린의 도움으로 마법을 익히고 용을 길들여 마을의 수호자로 만듭니다.',
    additionalOpinion:
      '흥미롭고 잘 짜여진 이야기를 만들었습니다. 다만, 캐릭터 발전이 더 깊었으면 좋았고, 전개가 다소 급하게 느껴졌습니다.',
    isAuthor: false,
  },
  {
    id: 3,
    title: '코드 생성 시도',
    author: 'CodeMaster',
    authorInitial: 'C',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-10T09:15:00Z',
    views: 800,
    satisfaction: 2.0,
    likes: 10,
    isLiked: false,
    bookmarks: 5,
    isBookmarked: false,
    platform: 'Google',
    model: 'Gemini 2.5 Flash',
    model_etc: '',
    category: '기타',
    category_etc: '',
    tags: [],
    prompt:
      '뉴스 웹사이트에서 헤드라인을 스크래핑하여 CSV 파일에 저장하는 Python 스크립트를 생성해 주세요.',
    aiResponse:
      '헤드라인을 스크래핑하려면 BeautifulSoup과 requests 라이브러리를 사용할 수 있습니다. 먼저 GET 요청을 보내고, HTML을 파싱하여 <h1> 또는 <h2> 태그 내의 텍스트를 추출한 후, csv 모듈을 사용하여 파일에 씁니다.',
    additionalOpinion:
      '응답은 일반적인 접근 방식을 제공했지만, 구체적인 코드 예시가 부족하여 구현에 도움이 되지 않았습니다.',
    isAuthor: false,
  },
  {
    id: 4,
    title: '기술 문서 번역',
    author: 'TranslatorX',
    authorInitial: 'T',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-20T11:45:00Z',
    views: 1200,
    satisfaction: 4.0,
    likes: 30,
    isLiked: true,
    bookmarks: 15,
    isBookmarked: true,
    platform: 'xAI',
    model: '기타',
    model_etc: 'Grok-3 Custom',
    category: '번역',
    category_etc: '',
    tags: ['번역', '언어'],
    prompt:
      "다음 소프트웨어 매뉴얼 발췌문을 독일어로 번역해 주세요: 'The system requires regular updates to maintain security and performance.'",
    aiResponse:
      'Das System erfordert regelmäßige Updates, um Sicherheit und Leistung aufrechtzuerhalten.',
    additionalOpinion:
      '기술 용어를 정확하게 처리하여 유창하고 일관된 번역을 제공했습니다. 수작업 시간을 크게 절약할 수 있었습니다.',
    isAuthor: false,
  },
  {
    id: 5,
    title: '뉴스 기사 요약',
    author: 'SummaryKing',
    authorInitial: 'S',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-15T16:00:00Z',
    views: 2500,
    satisfaction: 3.0,
    likes: 20,
    isLiked: false,
    bookmarks: 8,
    isBookmarked: false,
    platform: 'Meta',
    model: 'Llama 4 Scout',
    model_etc: '',
    category: '요약',
    category_etc: '',
    tags: ['뉴스', '요약'],
    prompt: '최근 재생 에너지 개발에 관한 이 기사의 주요 요점을 요약해 주세요.',
    aiResponse:
      '기사는 태양광 및 풍력 에너지 기술의 최근 발전을 논의하며, 효율성 증가와 비용 감소를 강조합니다. 또한 정부 인센티브와 전 세계적으로 재생 에너지 채택이 증가하고 있음을 언급합니다.',
    additionalOpinion:
      '요약은 주요 아이디어를 잘 포착했지만, 기사에서 언급된 특정 기술 혁신에 대한 중요한 세부 사항을 놓쳤습니다.',
    isAuthor: false,
  },
  {
    id: 6,
    title: '웹 앱 생성 시도',
    author: 'WebDevPro',
    authorInitial: 'W',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-05T13:30:00Z',
    views: 600,
    satisfaction: 1.5,
    likes: 5,
    isLiked: false,
    bookmarks: 2,
    isBookmarked: false,
    platform: 'Mistral',
    model: 'Magistral Small',
    model_etc: '',
    category: '개발/프로그래밍',
    category_etc: '',
    tags: ['코딩', '자동화'],
    prompt:
      'HTML, CSS, JavaScript를 사용하여 간단한 할 일 목록 웹 애플리케이션의 코드를 생성해 주세요.',
    aiResponse:
      '할 일 목록 앱을 만들려면 입력 필드와 목록 요소가 있는 HTML 구조가 필요합니다. CSS로 스타일을 지정하고 JavaScript로 작업을 동적으로 추가 및 제거합니다. 예를 들어, DOM API를 사용하여 목록 항목을 조작할 수 있습니다.',
    additionalOpinion:
      '응답은 기본적인 지침을 제공했지만, 실제 코드를 포함하지 않아 실질적인 도움이 되지 않았습니다. 구체적인 예시가 필요했습니다.',
    isAuthor: false,
  },
  {
    id: 7,
    title: '챗봇 대화 테스트',
    author: 'ChatBotGuru',
    authorInitial: 'C',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-25T08:00:00Z',
    views: 1800,
    satisfaction: 4.0,
    likes: 35,
    isLiked: true,
    bookmarks: 12,
    isBookmarked: true,
    platform: 'Perplexity',
    model: 'Sonar',
    model_etc: '',
    category: '기획/아이디어',
    category_etc: '',
    tags: ['챗봇', 'AI'],
    prompt:
      '고객 서비스 챗봇을 위한 대화 흐름을 설계해 주세요. 사용자가 제품에 대해 문의하고, 주문을 추적하며, 환불을 요청할 수 있어야 합니다.',
    aiResponse:
      '챗봇은 먼저 사용자에게 인사하고, 어떤 도움이 필요한지 묻습니다. 사용자가 제품 문의를 선택하면, 챗봇은 제품 카테고리를 묻고 관련 정보를 제공합니다. 주문 추적을 선택하면, 주문 번호를 입력받아 상태를 알려줍니다. 환불 요청 시, 챗봇은 필요한 정보를 수집하여 처리합니다.',
    additionalOpinion:
      '논리적이고 사용자 친화적인 대화 흐름을 설계했습니다. 실제 구현에 유용할 것 같습니다.',
  },
  {
    id: 8,
    title: '번역 경험',
    author: 'LangExplorer',
    authorInitial: 'L',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-10T12:00:00Z',
    views: 900,
    satisfaction: 2.5,
    likes: 15,
    isLiked: false,
    bookmarks: 3,
    isBookmarked: false,
    platform: '기타',
    model: '기타',
    model_etc: 'DeepSeek R-1',
    category: '번역',
    category_etc: '',
    tags: ['일본어', '번역'],
    prompt:
      "다음 문장을 일본어로 번역해 주세요: '오늘 날씨가 정말 좋네요. 산책하기 딱 좋은 날입니다.'",
    aiResponse: '今日は天気が本当にいいですね。散歩するのに最適な日です。',
    additionalOpinion:
      "번역은 대체로 정확했지만, '딱 좋은'의 뉘앙스가 완벽하게 전달되지 않은 것 같습니다. 더 자연스러운 표현이 필요할 수 있습니다.",
  },
  {
    id: 9,
    title: '보고서 작성',
    author: 'ReportWriter',
    authorInitial: 'R',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-01T15:45:00Z',
    views: 2000,
    satisfaction: 4.5,
    likes: 40,
    isLiked: true,
    bookmarks: 18,
    isBookmarked: true,
    platform: 'OpenAI',
    model: '기타',
    model_etc: 'GPT-4 Turbo',
    category: '업무/문서',
    category_etc: '',
    tags: [],
    prompt:
      '최근 프로젝트의 성과를 요약한 보고서를 작성해 주세요. 주요 성과, 도전 과제, 그리고 향후 계획을 포함해 주세요.',
    aiResponse:
      '지난 프로젝트에서 팀은 매출 20% 증가라는 주요 성과를 달성했습니다. 그러나 공급망 지연이라는 도전 과제에 직면했습니다. 향후 계획으로는 공급망 최적화와 새로운 시장 진출이 포함됩니다.',
    additionalOpinion:
      '간결하고 명확한 보고서를 작성하여 시간을 절약해 주었습니다. 내용이 잘 정리되어 있어 만족스럽습니다.',
  },
  {
    id: 10,
    title: '데이터 시각화',
    author: 'Admin',
    authorInitial: 'A',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-30T17:00:00Z',
    views: 700,
    satisfaction: 3.0,
    likes: 12,
    isLiked: false,
    bookmarks: 4,
    isBookmarked: false,
    platform: 'Anthropic',
    model: 'Claude 3.7 Sonnet',
    model_etc: '',
    category: '데이터/분석',
    category_etc: '',
    tags: ['시각화', '데이터'],
    prompt:
      '판매 데이터를 시각화하기 위한 차트 유형을 추천해 주세요. 연도별 매출 추이를 보여주고 싶습니다.',
    aiResponse:
      '연도별 매출 추이를 보여주기 위해 선 그래프를 사용하는 것이 좋습니다. 각 연도를 x축에, 매출을 y축에 표시하여 시간에 따른 변화를 명확히 볼 수 있습니다.',
    additionalOpinion:
      '추천은 타당했지만, 더 다양한 차트 유형이나 디자인 팁이 있으면 좋았을 것 같습니다.',
  },
  {
    id: 11,
    title: '교육 콘텐츠 생성',
    author: 'EduCreator',
    authorInitial: 'E',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-20T09:30:00Z',
    views: 1600,
    satisfaction: 4.0,
    likes: 28,
    isLiked: true,
    bookmarks: 14,
    isBookmarked: true,
    platform: 'Google',
    model: 'Gemini 2.5 Pro',
    model_etc: '',
    category: '교육/학습',
    category_etc: '',
    tags: [],
    prompt:
      '초등학생을 위한 간단한 과학 실험을 설명하는 교육 콘텐츠를 작성해 주세요. 실험은 안전하고 집에서 쉽게 할 수 있어야 합니다.',
    aiResponse:
      '물의 밀도를 보여주는 실험: 물에 소금, 설탕, 밀가루를 각각 넣고, 각 용액에 계란을 넣어 떠오르는지 가라앉는지 관찰합니다. 이를 통해 밀도의 차이를 이해할 수 있습니다.',
    additionalOpinion:
      '아이들이 이해하기 쉬운 간단하고 재미있는 실험을 제안했습니다. 교육적 가치가 높습니다.',
  },
  {
    id: 12,
    title: '이메일 초안 작성',
    author: 'EmailComposer',
    authorInitial: 'E',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-15T11:00:00Z',
    views: 1300,
    satisfaction: 3.5,
    likes: 22,
    isLiked: false,
    bookmarks: 6,
    isBookmarked: false,
    platform: 'xAI',
    model: 'Grok-4',
    model_etc: '',
    category: '업무/문서',
    category_etc: '',
    tags: ['이메일', '작성'],
    prompt:
      '클라이언트에게 프로젝트 진행 상황을 업데이트하는 이메일을 작성해 주세요. 현재 진행 중인 작업과 다음 단계를 포함해 주세요.',
    aiResponse:
      '안녕하세요 [클라이언트 이름]님,\n\n현재 프로젝트는 예정대로 진행되고 있습니다. 현재 [작업 내용]을 완료했으며, 다음 단계로 [다음 작업]을 진행할 예정입니다. 추가 질문이 있으시면 언제든지 연락 주세요.\n\n감사합니다,\n[당신의 이름]',
    additionalOpinion:
      '기본적인 이메일 초안을 제공했지만, 좀 더 개인화된 톤이나 구체적인 세부 사항이 추가되면 좋았을 것 같습니다.',
  },
  {
    id: 13,
    title: '마케팅 전략 수립',
    author: 'MarketingGenius',
    authorInitial: 'M',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-10T14:00:00Z',
    views: 2200,
    satisfaction: 4.5,
    likes: 45,
    isLiked: true,
    bookmarks: 20,
    isBookmarked: true,
    platform: 'Meta',
    model: 'Llama 3.1',
    model_etc: '',
    category: '기획/아이디어',
    category_etc: '',
    tags: [],
    prompt:
      '새로운 제품 출시를 위한 마케팅 전략을 제안해 주세요. 타겟 고객은 20-30대 젊은 층입니다.',
    aiResponse:
      '20-30대 젊은 층을 타겟으로 하는 마케팅 전략으로는 소셜 미디어 캠페인, 인플루언서 마케팅, 그리고 체험 이벤트가 효과적입니다. 또한, 지속 가능성과 개인화를 강조하는 메시지를 전달하는 것이 중요합니다.',
    additionalOpinion:
      '타겟 고객에 맞는 창의적이고 실용적인 전략을 제안했습니다. 특히 인플루언서 마케팅 아이디어가 마음에 들었습니다.',
  },
  {
    id: 14,
    title: '웹사이트 디자인',
    author: 'DesignMaven',
    authorInitial: 'D',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-25T10:15:00Z',
    views: 500,
    satisfaction: 2.0,
    likes: 8,
    isLiked: false,
    bookmarks: 1,
    isBookmarked: false,
    platform: 'Mistral',
    model: 'Mistral Small 3',
    model_etc: '',
    category: '창작/글쓰기',
    category_etc: '',
    tags: ['디자인', '웹'],
    prompt: '현대적이고 미니멀한 스타일의 웹사이트 디자인을 위한 레이아웃을 제안해 주세요.',
    aiResponse:
      '미니멀한 웹사이트 디자인을 위해서는 깔끔한 타이포그래피, 충분한 여백, 그리고 단색 배경을 사용하는 것이 좋습니다. 내비게이션은 간단하게 유지하고, 콘텐츠를 중심으로 배치하세요.',
    additionalOpinion:
      '일반적인 디자인 원칙을 설명했지만, 구체적인 레이아웃 예시나 시각적 세부 사항이 부족했습니다.',
  },
  {
    id: 15,
    title: '음악 작곡',
    author: 'MusicMaestro',
    authorInitial: 'M',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-20T12:30:00Z',
    views: 1100,
    satisfaction: 3.5,
    likes: 18,
    isLiked: true,
    bookmarks: 7,
    isBookmarked: false,
    platform: 'Perplexity',
    model: 'R1 1776',
    model_etc: '',
    category: '기타',
    category_etc: '작곡',
    tags: [],
    prompt: '간단한 피아노 멜로디를 위한 악보를 제안해 주세요. 초보자도 연주할 수 있어야 합니다.',
    aiResponse:
      'C 메이저 스케일로 시작하여, C-G-C-E-G와 같은 간단한 패턴을 반복합니다. 4/4 박자에 맞춰 각 음을 1박씩 연주하세요.',
    additionalOpinion:
      '초보자에게 적합한 간단한 멜로디를 제안했지만, 더 창의적인 변주가 추가되면 좋았을 것 같습니다.',
  },
  {
    id: 16,
    title: '비즈니스 제안서 작성',
    author: 'BizProposer',
    authorInitial: 'B',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-18T15:00:00Z',
    views: 1400,
    satisfaction: 4.0,
    likes: 25,
    isLiked: true,
    bookmarks: 10,
    isBookmarked: true,
    platform: 'xAI',
    model: 'Grok-4',
    model_etc: '',
    category: '업무/문서',
    category_etc: '',
    tags: ['비즈니스', '제안'],
    prompt:
      '신규 클라이언트를 위한 비즈니스 제안서 초안을 작성해 주세요. 목표와 예상 수익을 포함해 주세요.',
    aiResponse:
      '제안서는 회사의 목표인 시장 점유율 10% 증가를 달성하기 위한 전략을 설명합니다. 예상 수익은 첫 해에 5천만 원이며, 마케팅 및 제품 개발에 초점을 맞춥니다.',
    additionalOpinion:
      '구체적이고 설득력 있는 초안을 제공했습니다. 클라이언트 맞춤형 세부 사항이 더 추가되면 완벽할 것 같습니다.',
  },
  {
    id: 17,
    title: '고객 피드백 분석',
    author: 'FeedbackAnalyzer',
    authorInitial: 'F',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-05T09:45:00Z',
    views: 950,
    satisfaction: 3.0,
    likes: 15,
    isLiked: false,
    bookmarks: 3,
    isBookmarked: false,
    platform: 'OpenAI',
    model: 'o4-mini',
    model_etc: '',
    category: '데이터/분석',
    category_etc: '',
    tags: [],
    prompt: '고객 피드백 데이터를 분석하여 주요 불만 사항을 식별해 주세요.',
    aiResponse:
      '고객 피드백을 분석한 결과, 배송 지연과 고객 서비스 응답 시간이 주요 불만 사항으로 나타났습니다. 약 30%의 응답이 이 두 가지 문제를 언급했습니다.',
    additionalOpinion:
      '주요 문제를 정확히 지적했지만, 해결 방안 제안이 포함되면 더 유용했을 것입니다.',
  },
  {
    id: 18,
    title: '소셜 미디어 콘텐츠 생성',
    author: 'SocialMediaStar',
    authorInitial: 'S',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-07-12T14:15:00Z',
    views: 3000,
    satisfaction: 4.5,
    likes: 60,
    isLiked: true,
    bookmarks: 25,
    isBookmarked: true,
    platform: 'Anthropic',
    model: 'Claude 3 Opus',
    model_etc: '',
    category: '기타',
    category_etc: '',
    tags: ['소셜 미디어', '콘텐츠'],
    prompt:
      '새로운 제품 홍보를 위한 소셜 미디어 게시물 초안을 작성해 주세요. 짧고 매력적이어야 합니다.',
    aiResponse:
      '✨ 새로 출시된 [제품명]을 만나보세요! 혁신적인 디자인과 놀라운 성능으로 여러분의 일상을 바꿉니다. 지금 확인하세요! #신제품 #혁신',
    additionalOpinion:
      '간결하고 매력적인 게시물을 작성했습니다. 해시태그 선택도 적절해서 소셜 미디어에 잘 맞습니다.',
  },
  {
    id: 19,
    title: '시나리오 작성',
    author: 'ScenarioWriter',
    authorInitial: 'S',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-06-30T13:00:00Z',
    views: 850,
    satisfaction: 3.5,
    likes: 18,
    isLiked: false,
    bookmarks: 5,
    isBookmarked: false,
    platform: 'Google',
    model: 'Gemini 1.5 Pro',
    model_etc: '',
    category: '개발/프로그래밍',
    category_etc: '',
    tags: [],
    prompt: '간단한 모바일 앱의 사용자 시나리오를 작성해 주세요. 앱은 날씨 정보를 제공합니다.',
    aiResponse:
      '사용자가 앱을 열고 위치를 입력하면, 앱은 현재 날씨와 주간 예보를 표시합니다. 사용자는 알림 설정을 통해 특정 날씨 조건에 대한 경고를 받을 수 있습니다.',
    additionalOpinion:
      '기본적인 시나리오를 제공했지만, 사용자 경험을 개선할 수 있는 세부적인 기능 제안이 더 있으면 좋았을 것 같습니다.',
  },
  {
    id: 20,
    title: '법률 문서 검토',
    author: 'Admin',
    authorInitial: 'A',
    avatarSrc: '/placeholder-user.jpg',
    createdAt: '2025-05-22T16:30:00Z',
    views: 1700,
    satisfaction: 4.0,
    likes: 32,
    isLiked: true,
    bookmarks: 15,
    isBookmarked: true,
    platform: '기타',
    model: '기타',
    model_etc: 'Another Model Y',
    category: '업무/문서',
    category_etc: '',
    tags: ['법률', '문서'],
    prompt: '간단한 계약서 초안을 검토하고 개선할 부분을 제안해 주세요.',
    aiResponse:
      '계약서의 조항은 명확하지만, 책임 한계와 분쟁 해결 절차가 부족합니다. 이 두 가지를 추가하여 법적 보호를 강화하는 것이 좋습니다.',
    additionalOpinion:
      '중요한 개선점을 잘 지적했습니다. 제안이 실질적이어서 계약서를 더 튼튼하게 만들 수 있었습니다.',
  },
]
