# Generated by Django 4.2.23 on 2025-07-01 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='로그인에 사용될 이메일 주소', max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(help_text='고유한 사용자 식별자 (자동 생성)', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='사용자명')),
                ('is_active', models.BooleanField(default=True, help_text='계정 활성화 여부', verbose_name='활성 상태')),
                ('is_staff', models.BooleanField(default=False, help_text='관리자 사이트 접근 권한', verbose_name='스태프 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='계정 생성 일시', verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='계정 정보 최종 수정 일시', verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, help_text='개인 웹사이트 또는 블로그 URL', verbose_name='웹사이트')),
                ('location', models.CharField(blank=True, help_text='거주 지역 또는 활동 지역', max_length=100, verbose_name='위치')),
                ('avatar', models.ImageField(blank=True, help_text='프로필 사진 (선택사항)', null=True, upload_to='avatars/%Y/%m/', verbose_name='프로필 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='auth_user_usernam_f2740e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='auth_user_created_2cecd0_idx'),
        ),
    ]
