# Generated by Django 4.2.23 on 2025-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.PositiveSmallIntegerField(default=0, help_text='기본 아바타의 그라디언트 색상 인덱스', verbose_name='아바타 색상'),
        ),
    ]
