# Generated by Django 4.2.23 on 2025-07-01 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_avatar_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_password_change",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="마지막 비밀번호 변경 일시",
                verbose_name="비밀번호 변경일",
            ),
            preserve_default=False,
        ),
    ]
