# Generated by Django 4.2.23 on 2025-07-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_last_password_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_password_change",
        ),
    ]
