# Generated by Django 5.2.4 on 2025-07-26 08:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='플랫폼명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '플랫폼',
                'verbose_name_plural': '플랫폼',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모델명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='posts.platform', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '모델',
                'verbose_name_plural': '모델',
                'ordering': ['platform__name', 'name'],
                'unique_together': {('platform', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200)], verbose_name='제목')),
                ('model_etc', models.CharField(blank=True, max_length=100, verbose_name='기타 모델명')),
                ('category_etc', models.CharField(blank=True, max_length=100, verbose_name='기타 카테고리명')),
                ('tags', models.TextField(blank=True, default='', verbose_name='태그')),
                ('prompt', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='프롬프트')),
                ('ai_response', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='AI 응답')),
                ('additional_opinion', models.TextField(blank=True, default='', verbose_name='추가 의견')),
                ('satisfaction', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='만족도')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('bookmark_count', models.PositiveIntegerField(default=0, verbose_name='북마크 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.category', verbose_name='카테고리')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.model', verbose_name='모델')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.platform', verbose_name='플랫폼')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='좋아요 여부')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='북마크 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '게시글 상호작용',
                'verbose_name_plural': '게시글 상호작용',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform'], name='posts_post_platfor_72ffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='posts_post_categor_b0a4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='posts_post_author__19d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['user', 'post'], name='posts_posti_user_id_9114aa_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['is_liked'], name='posts_posti_is_like_7737da_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['is_bookmarked'], name='posts_posti_is_book_09729c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postinteraction',
            unique_together={('user', 'post')},
        ),
    ]
