# Generated by Django 5.2.4 on 2025-07-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='model',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='model',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='updated_at',
        ),
    ]
