# Generated by Django 5.2.4 on 2025-07-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['id'], 'verbose_name': '모델', 'verbose_name_plural': '모델'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['id'], 'verbose_name': '플랫폼', 'verbose_name_plural': '플랫폼'},
        ),
    ]
