# Generated by Django 5.2.4 on 2025-08-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_options_alter_model_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='AiModel',
        ),
    ]
