# Generated by Django 5.2.4 on 2025-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_model_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='상세 모델명'),
        ),
    ]
