# Generated by Django 5.2.4 on 2025-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_model_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['platform__name', 'released_order', 'name'], 'verbose_name': '모델', 'verbose_name_plural': '모델'},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='released_at',
            field=models.DateField(blank=True, help_text='알려진 정확한 출시일이 있을 경우 설정합니다.', null=True, verbose_name='출시일'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='released_order',
            field=models.PositiveIntegerField(default=0, help_text='출시 순서를 나타내는 정수입니다. 낮을수록 먼저 출시된 모델입니다.', verbose_name='출시 순서'),
        ),
    ]
