# Generated by Django 5.2.4

from django.db import migrations, models
from django.utils.text import slugify
from django.utils import timezone


def populate_slugs_and_flags(apps, schema_editor):
    Platform = apps.get_model('posts', 'Platform')
    AiModel = apps.get_model('posts', 'AiModel')

    # Platform.slug 채우기
    for platform in Platform.objects.all():
        if not platform.slug:
            base = (platform.name or '').strip().lower()
            if base in {'기타', 'other'}:
                candidate = 'other'
            else:
                candidate = slugify(platform.name) or 'platform'

            unique = candidate
            suffix = 2
            while Platform.objects.filter(slug=unique).exclude(pk=platform.pk).exists():
                unique = f"{candidate}-{suffix}"
                suffix += 1
            platform.slug = unique
            if platform.created_at is None:
                platform.created_at = timezone.now()
            if platform.updated_at is None:
                platform.updated_at = timezone.now()
            platform.save(update_fields=['slug', 'created_at', 'updated_at'])

    # AiModel.slug 채우기 및 '기타' 보정
    for model in AiModel.objects.select_related('platform').all():
        if not model.slug:
            base_name = (model.name or '').strip()
            if base_name == '기타':
                candidate = 'other'
            else:
                candidate = slugify(base_name) or 'model'

            unique = candidate
            suffix = 2
            while AiModel.objects.filter(platform=model.platform, slug=unique).exclude(pk=model.pk).exists():
                unique = f"{candidate}-{suffix}"
                suffix += 1
            model.slug = unique
        # '기타' 모델은 상세 자유 입력 금지
        if model.name == '기타':
            model.variant_free_text_allowed = False
        model.save(update_fields=['slug', 'variant_free_text_allowed'])


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_add_release_fields'),
    ]

    operations = [
        # Platform 확장
        migrations.AddField(
            model_name='platform',
            name='slug',
            # SlugField는 기본적으로 db_index=True라 PostgreSQL에서 *_like 인덱스를 만듭니다.
            # 이후 unique=True로 AlterField할 때 동일한 *_like 인덱스명이 다시 생성되어 충돌할 수 있어
            # 초기 추가 단계에서는 db_index를 끕니다.
            field=models.SlugField(max_length=50, null=True, blank=True, verbose_name='슬러그', db_index=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='platform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시', null=True),
        ),

        # AiModel 확장
        migrations.AddField(
            model_name='aimodel',
            name='slug',
            field=models.SlugField(max_length=100, null=True, blank=True, verbose_name='슬러그'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='사용중단'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='deleted_at',
            field=models.DateTimeField(null=True, blank=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='variant_free_text_allowed',
            field=models.BooleanField(default=True, verbose_name='상세 모델 자유 입력 허용'),
        ),

        # 인덱스 추가
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['slug'], name='posts_plat_slug_idx'),
        ),
        # released_order 인덱스는 이후 마이그레이션에서 제거됨

        # 데이터 백필
        migrations.RunPython(populate_slugs_and_flags, migrations.RunPython.noop),

        # 제약 강화
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=50, unique=True, verbose_name='슬러그'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='슬러그'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=['platform', 'slug'], name='unique_model_slug_per_platform'),
        ),
    ]

