# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_platform_model_slug_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='released_order',
        ),
    ]


