# Generated by Django 5.2.4 on 2025-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_released_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['platform__name', 'name'], 'verbose_name': '모델', 'verbose_name_plural': '모델'},
        ),
        migrations.RenameIndex(
            model_name='platform',
            new_name='posts_platf_slug_8bc921_idx',
            old_name='posts_plat_slug_idx',
        ),
    ]
