# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0009_alter_aimodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['platform', 'sort_order'], name='posts_aimo_plat_sort_idx'),
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['platform__name', 'sort_order', 'name'], 'verbose_name': '모델', 'verbose_name_plural': '모델'},
        ),
    ]


