# Generated by Django 5.2.4 on 2025-08-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_aimodel_sort_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimodel',
            new_name='posts_aimod_platfor_00be21_idx',
            old_name='posts_aimo_plat_sort_idx',
        ),
    ]
