# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0011_rename_posts_aimo_plat_sort_idx_posts_aimod_platfor_00be21_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['model'], name='posts_post_model_idx'),
        ),
    ]


