# Generated by Django 5.2.4 on 2025-08-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_model_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_model_i_00884b_idx',
            old_name='posts_post_model_idx',
        ),
    ]
