# Generated by Django 5.2.4 on 2025-09-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_posts_post_model_idx_posts_post_model_i_00884b_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='variant_free_text_allowed',
        ),
    ]
