#!/bin/bash

# PromptHub 스크립트 도움말
# 사용 가능한 모든 스크립트를 보여줍니다

echo "🔧 PromptHub 개발 도구 모음"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 사용 가능한 스크립트들:"
echo ""
echo "🚀 개발 관련:"
echo "   ./scripts/setup.sh        - 🔧 프로젝트 초기 설정 (가상환경, 의존성, 마이그레이션)"
echo "   ./scripts/start-dev.sh    - 🌐 개발 서버 시작 (백엔드 + 프론트엔드)"
echo ""
echo "🗃️ 데이터베이스 관련:"
echo "   ./scripts/migrate.sh      - 🔄 데이터베이스 마이그레이션 실행"
echo "   ./scripts/reset-db.sh     - 🗑️  데이터베이스 완전 초기화 (주의!)"
echo ""
echo "ℹ️  기타:"
echo "   ./scripts/help.sh         - 📖 이 도움말 보기"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 사용법 예시:"
echo "   1️⃣ 처음 시작: ./scripts/setup.sh"
echo "   2️⃣ 개발 시작: ./scripts/start-dev.sh"
echo "   3️⃣ 모델 변경 후: ./scripts/migrate.sh"
echo "   4️⃣ 완전 초기화: ./scripts/reset-db.sh"
echo ""
echo "🔗 유용한 URL:"
echo "   🌐 프론트엔드:     http://localhost:3000"
echo "   🐍 백엔드 API:     http://localhost:8000/api/"
echo "   👨‍💼 관리자 페이지:   http://localhost:8000/admin/"
echo "   📚 API 문서:       http://localhost:8000/api/docs/"
echo ""
echo "🔑 기본 관리자 계정:"
echo "   📧 이메일: admin@prompthub.com"
echo "   🔒 비밀번호: admin123!"
echo ""
echo "💬 문제가 있으시면 README.md 파일을 확인해보세요!" 