# Generated by Django 5.2.4 on 2025-07-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_handle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub 핸들'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='위치'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 이미지'),
        ),
    ]
