# Generated by Django 5.2.4 on 2025-08-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio_customuser_github_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('data_sharing', models.BooleanField(default=False)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 설정',
                'verbose_name_plural': '사용자 설정들',
            },
        ),
    ]
