# Generated by Django 5.2.4 on 2025-08-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('posts', '0005_post_model_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingranking',
            name='related_model',
            field=models.ForeignKey(blank=True, help_text='이 트렌딩 랭킹과 연결된 AI 모델을 선택하세요. 선택하면 해당 모델로 작성된 게시글을 보여줍니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_rankings', to='posts.aimodel', verbose_name='관련 모델'),
        ),
    ]
