# Generated by Django 5.2.4 on 2025-08-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_related_model_to_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingranking',
            name='model_detail_contains',
            field=models.CharField(blank=True, help_text="게시글의 model_detail 필드에 포함되어야 할 텍스트 (예: 'Sonnet', 'oss')", max_length=100, verbose_name='모델 상세명 포함 조건'),
        ),
        migrations.AddField(
            model_name='trendingranking',
            name='model_etc_contains',
            field=models.CharField(blank=True, help_text="게시글의 model_etc 필드에 포함되어야 할 텍스트 (예: 'GPT oss 20b')", max_length=100, verbose_name='기타 모델명 포함 조건'),
        ),
        migrations.AddField(
            model_name='trendingranking',
            name='use_exact_matching',
            field=models.BooleanField(default=False, help_text='활성화하면 아래 조건들을 추가로 적용하여 더 정확한 게시글 매칭을 수행합니다.', verbose_name='정확한 매칭 사용'),
        ),
    ]
