# Generated by Django 5.2.4 on 2025-08-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0, verbose_name='총 게시글 수')),
                ('total_users', models.IntegerField(default=0, verbose_name='총 사용자 수')),
                ('total_views', models.BigIntegerField(default=0, verbose_name='총 조회수')),
                ('total_likes', models.BigIntegerField(default=0, verbose_name='총 좋아요 수')),
                ('total_bookmarks', models.BigIntegerField(default=0, verbose_name='총 북마크 수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
            ],
            options={
                'verbose_name': '대시보드 통계',
                'verbose_name_plural': '대시보드 통계',
            },
        ),
    ]
